### ISSUE TITLE
Want to understand better why native extensions are failing on CircleCI

### ISSUE THREAD

**Issue by kigster** [bazelruby/rules_ruby#24]
I managed to get CircleCI build passing for the https://github.com/bazelruby/ruby-monorepo repository, but only after I removed `rubocop` and other gems that depended on gems needing native extensions. I am able to install rubocop and run it on CI via a BASH script, but not via Bazel.

Here is one example CI build that failed installing a gem with native extension:
https://app.circleci.com/jobs/github/bazelruby/ruby-monorepo/40

The actual error is this:

```
ake "DESTDIR="
compiling adj_matrix.c
gcc: error trying to exec 'cc1': execvp: No such file or directory
make: *** [Makefile:245: adj_matrix.o] Error 1
```

**Comment by yugui** [comment]
Is this issue already fixed in master?

**Comment by kigster** [comment]
So, rubocop depends on a gem with a native extension. The build passed after I removed rubocop from the gemfile and installed it manually. 

Here is the build that failed while rubocop was still in the gemfile:

https://app.circleci.com/jobs/github/bazelruby/ruby-monorepo/40/parallel-runs/0/steps/0-105

**Comment by kigster** [comment]
It appears that changing JVM args to increase memory fixes this issue, and native extension are able to be built. This + removing `env -i`.
