### ISSUE TITLE
When using a local ruby installation it includes the local `LOAD_PATH`

### ISSUE THREAD

**Issue by grahamjenson** [bazelruby/rules_ruby#44]
The problem is that if the ruby interpreter uses the ruby already installed on the host, and that host is rbenv, rbenv will inject into its own `LOAD_PATH` which includes its gems folders.

This means that `ruby_binary` is not hermetic as it may inadvertently depend on gems that are not explicitly declared in the rule.

Not sure how to fix this, maybe use a better script to use the local ruby version, and try work around rbenvs magic (or use rbenvs magic to find the real interpreter path without LOAD_PATH injection)

**Comment by kigster** [comment]
We don’t have to use rbenv’s shims or wrappers for the ruby binary. It installs rubies in .rbenv/versions/2.6.5/bin/ruby — that would be a pure binary without any rbenv or Rvm magic.
