### ISSUE TITLE
`ruby_bundle` should support local gems

### ISSUE THREAD

**Issue by shs96c** [bazelruby/rules_ruby#62]
It is sometimes helpful to commit gems into a source repository and use them from there (eg. Selenium vendors all gems into our tree to avoid issues with slow networks at build time). `ruby_bundle` should support this use case in some way.

https://github.com/SeleniumHQ/selenium/tree/master/third_party/rb

**Comment by kigster** [comment]
That’s a good point.

Where do you typically put your gems? Are they stored as .gem files? Do you use bundler to cache gem files?

**Comment by kigster** [comment]
Never mind I see how it’s stored.
