### ISSUE TITLE
Move ruby files under ruby_rules/examples into a mini-mono repo

### ISSUE THREAD

**Issue by kigster** [bazelruby/rules_ruby#8]
Move `examples/**/*` to `examples/apps/foo-bar/**/*` and make ruby files under `//apps/foo-bar` work Bazel Targets.

**Comment by yugui** [comment]
IMO, it is better to keep them in the current location because:
* It is more convenient for users, unless the example tree is too large to download together with the rules.
* It is easier to make sure that the rules are able to build the examples in CI.

**Comment by kigster** [comment]
Given that we will have a complex tree hierarchy inside the [ruby-monorepo](https://github.com/bazelruby/ruby-monorepo) project, I agree with you. Closing this ticket.
