### ISSUE TITLE
Setup script attempts to delete ~/.rbenv if rbenv is installed with Homebrew

### ISSUE THREAD

**Issue by shepting** [bazelruby/rules_ruby#81]
I can't tell for sure, but the setup script seems to try to delete `~/.rbenv` if there is no `bin/rbenv` executable inside there. I believe that Homebrew installs the `rbenv` binary in `/usr/oca/bin/rbenv`.

I tried to run the `bin/setup` command on my Mac, but then was worried that it seemed to want to delete `~/.rbenv`.
![Screen Shot 2020-09-29 at 4 38 07 PM](https://user-images.githubusercontent.com/48065/94627536-b5874300-0272-11eb-814b-f0d92eec14e5.png)

My `~/.rbenv` just has `shims` and `versions` whereas my `rbenv` executable comes from `/usr/local/bin/rbenv`:
![Screen Shot 2020-09-29 at 4 40 20 PM](https://user-images.githubusercontent.com/48065/94627567-c932a980-0272-11eb-9294-4fb404cd95f0.png)

**Comment by shepting** [comment]
I think that this is the chunk that should likely be updated: https://github.com/bazelruby/rules_ruby/blob/master/bin/setup#L44-L48

**Comment by shepting** [comment]
I believe the proper approach would be to run `rbenv install 2.7.1` with `rbenv` if it's installed. The setup script is then able to run flawlessly:

![Uploading Screen Shot 2020-09-29 at 4.54.52 PM.png…]()

**Comment by shepting** [comment]
![Screen Shot 2020-09-29 at 4 54 52 PM](https://user-images.githubusercontent.com/48065/94628441-dea8d300-0274-11eb-8495-fd698c7cca56.png)

**Comment by kigster** [comment]
Yikes, I don't remember why it as trying to delete it but I'll take a look and fix it. Thanks for reporting!
