### ISSUE TITLE
require_paths attribute does not work

### ISSUE THREAD

**Issue by ash2k** [bazelruby/rules_ruby#97]
https://github.com/bazelruby/rules_ruby/blob/b738b9885f3fba30cbbb6fc05f23ae7a78a4ca84/ruby/private/gemspec/def.bzl#L101 hard codes it to `lib`.

**Comment by kigster** [comment]
Yes, it's a known limitation — thank you for taking on the enhancement and let me know if you want any help. 

We can remote pair on this if you like.
